version: '3.9'
services:
  api_service:
    image:  danielggm/accidents_model_server:latest
    container_name: model_server
    ports: 
      - target: 8080
        published: 8080
      - target: 8081
        published: 8081
    environment:
      - MLSERVER_HTTP_PORT=8083
      - MLSERVER_LOAD_MODELS_AT_STARTUP=True
      - MLSERVER_METRICS_PORT=8082
    
  
# networks:
#   my_network:  
#     ipam:
#       config:
#         - subnet: 172.50.0.0/16
#           gateway: 172.50.0.1