version: "3.9"
services:
  model:
    image: danielggm/accidents_model_server:latest
    #image: general_model_server:latest
    container_name: model
    networks:
      - api_net
    ports:
      - target: 8080
        published: 8080

  mlflow:
    image: mlflow_server:latest
    container_name: mlflow
    ports:
      - target: 8000
        published: 8000
      # target host : published container
    networks:
      - api_net
    volumes:
      - ./mlflow/mlruns:/mlflow/mlruns
    command: mlflow server --host 0.0.0.0 --port 8000
  
  model_api:
    image:   model_api:latest
    container_name: model_api
    ports:
      - target: 8050
        published: 8050
      # target host : published container
    networks:
      - api_net
    volumes:
      - ./mlflow:/mlflow
    #command: mlflow server --host 0.0.0.0 --port 8000

  api:
    image: project_api:latest
    container_name: api
    networks:
      - api_net
    ports:
      - "8090:8090"
    expose:
      - 8090
    depends_on:
      - model

  streamlit:
    image: project_streamlit:latest
    container_name: streamlit
    networks:
      - api_net
    ports:
      - "8501:8501"
    depends_on:
      - api
    privileged: true

  database:
    image: database_api:latest
    container_name: database
    networks:
      - api_net
    ports:
      - "9090:9090"

networks:
  api_net:
