# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "daniel" ]
  pull_request:
    branches: [ "daniel" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # - name: Lint with flake8
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    # - name: Test with pytest
    #   run: |
    #     pytest
    - name: Run all containers
      run: |
        bash setup.sh
        sleep 10  # Wait for the container to start
        CONTAINER_ID_1=$(docker-compose -f docker-compose/docker-compose.yml ps -q model)
        CONTAINER_ID_2=$(docker-compose -f docker-compose/docker-compose.yml ps -q mlflow)
        CONTAINER_ID_3=$(docker-compose -f docker-compose/docker-compose.yml ps -q model_api)
        CONTAINER_ID_4=$(docker-compose -f docker-compose/docker-compose.yml ps -q api)
        CONTAINER_ID_5=$(docker-compose -f docker-compose/docker-compose.yml ps -q streamlit)
        CONTAINER_ID_6=$(docker-compose -f docker-compose/docker-compose.yml ps -q database)
        export $CONTAINER_ID_1
        export $CONTAINER_ID_2
        export $CONTAINER_ID_3
        export $CONTAINER_ID_4
        export $CONTAINER_ID_5
        export $CONTAINER_ID_6

    - name: Run curl tests
      run: |
        curl http://localhost:8050/status -X GET
     #    CONTAINER_ID=$(docker-compose -f docker-compose/docker-compose.yml ps -q model_api)


    - name: Run tests
      run: python workflow_test.py 
      # $CONTAINER_ID_1 $CONTAINER_ID_2 $CONTAINER_ID_3  $CONTAINER_ID_4 $CONTAINER_ID_5 $CONTAINER_ID_6

    - name: Stop Docker containers
      run: docker-compose -f docker-compose/docker-compose.yml down
